name: biorobert_mimic
ckpt_dir: ckpt

dataset:
  proto: Seq2Seq
  src:
    root: data/RRS/mimic-cxr/
    file: findings.tok
    tokenizer: allenai/biomed_roberta_base # edit this
    tokenizer_max_len: 128
  tgt:
    root: data/RRS/mimic-cxr/
    file: impression.tok
    tokenizer: allenai/biomed_roberta_base # edit this
    tokenizer_max_len: 80

model:
  proto: SumHugMono
  encoder:
    proto: allenai/biomed_roberta_base # edit this
  decoder:
    proto: allenai/biomed_roberta_base # edit this

trainor:
  batch_size: 128
  optimizer: RAdam
  optim_params:
    lr: 0.00005
    weight_decay: 0.
  lr_decay: ReduceLROnPlateau
  lr_decay_params:
    factor: 0.8
    patience: 1
    min_lr: 0.000001
    threshold_mode: abs
  epochs: 99
  early_stop: 10
  eval_start: 0
  early_stop_metric: ROUGE2

validator:
  batch_size: 4
  beam_width: 8
  metrics: [ROUGEL, ROUGE2, BLEU]
  splits: [validate]


ensemblor:
  batch_size: 16
  beam_width: 8
  metrics: [ROUGEL, ROUGE2, BLEU]
  splits: [validate, test]
  mode: all
